// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz7PsfXEAnJXY7Jc1cAq4ueKnbwZ2X9to',
    appId: '1:189887749916:web:6935ce59d0534d9b2ce4d9',
    messagingSenderId: '189887749916',
    projectId: 'workshopmanagementsystem-c80c6',
    authDomain: 'workshopmanagementsystem-c80c6.firebaseapp.com',
    storageBucket: 'workshopmanagementsystem-c80c6.firebasestorage.app',
    measurementId: 'G-CJKFH83W00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeJLpjLX_t6Tr7L-R6kAsFJTBBaUyiLSc',
    appId: '1:189887749916:android:45e47da3edbf5e552ce4d9',
    messagingSenderId: '189887749916',
    projectId: 'workshopmanagementsystem-c80c6',
    storageBucket: 'workshopmanagementsystem-c80c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW_pBj5-Moy5Sz7Z9cX_uLVxgBZw55KwE',
    appId: '1:189887749916:ios:8da2731fd01590452ce4d9',
    messagingSenderId: '189887749916',
    projectId: 'workshopmanagementsystem-c80c6',
    storageBucket: 'workshopmanagementsystem-c80c6.firebasestorage.app',
    iosBundleId: 'com.example.workshopManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW_pBj5-Moy5Sz7Z9cX_uLVxgBZw55KwE',
    appId: '1:189887749916:ios:8da2731fd01590452ce4d9',
    messagingSenderId: '189887749916',
    projectId: 'workshopmanagementsystem-c80c6',
    storageBucket: 'workshopmanagementsystem-c80c6.firebasestorage.app',
    iosBundleId: 'com.example.workshopManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz7PsfXEAnJXY7Jc1cAq4ueKnbwZ2X9to',
    appId: '1:189887749916:web:6935ce59d0534d9b2ce4d9',
    messagingSenderId: '189887749916',
    projectId: 'workshopmanagementsystem-c80c6',
    authDomain: 'workshopmanagementsystem-c80c6.firebaseapp.com',
    storageBucket: 'workshopmanagementsystem-c80c6.firebasestorage.app',
    measurementId: 'G-CJKFH83W00',
  );

}